### ISSUE TITLE
Doesn't work on Anki 2.1.43

### ISSUE THREAD

**Issue by andynvo** [itsmepvr/anki-find-and-replace-in-templates#1]
Hi, this add-on doesn't work (on plain text, html tags, or symbols) when I installed it for my version of Anki.  Can you help me troubleshoot?

**Comment by itsmepvr** [comment]
Strangely, it's working perfectly fine in Anki 2.1.44 . Can you share any
image of the issue? Is it GUI or replacement that doesn't work?

**Comment by andynvo** [comment]
Hi, the GUI is fine; the replacement isn't working.  I'm trying to do massive replacement of certain words and phrases in my cards and reformat some of them. It would take me forever to do so individually, so I was hoping that your add-on could help, but nothing seems to happen when I click "replace".

**Comment by itsmepvr** [comment]
Since you mentioned `massive replacement` there might be a space or new
line or special character mismatch. Can be traced out. Can you send a
sample of text that you are trying to replace?

**Comment by itsmepvr** [comment]
Updated for <= v2.1.65
