### ISSUE TITLE
Changes are not saved 

### ISSUE THREAD

**Issue by jcznk** [itsmepvr/anki-find-and-replace-in-templates#2]
Hello, first and foremost thank you for the add-on. Much needed functionality.

In Anki 2.1.55 (but I guess also in some previous versions):
after using the Find and Replace function, the changes are not saved unless you go open the template editor and click Save. This is especially incovenient when you use Find and Replace to batch edit all the notetypes in your collection. I think the reason may be that, at the time of the add-on's publication, Anki had not introduced yet the "Save" function/button when editing templates?

**Comment by itsmepvr** [comment]
Hi, yes the issue is with the save button only. I had tested this for 2.1.44 version only. Will update soon for earlier versions. 
Thanks

**Comment by itsmepvr** [comment]
Updated for <= v2.1.65
