### ISSUE TITLE
Anki 2.1.61 (0c1eaf4c)⁩

### ISSUE THREAD

**Issue by Derancli** [itsmepvr/anki-find-and-replace-in-templates#3]
Hi,
Thanks for this add-on but I get the impression it only works partially with latest Anki version (not all occurrences are replaced, you need to go into the template editor and it also produces an error message on start-up). If you could update it, it would be a great help.
Thanks

**Comment by itsmepvr** [comment]
Yup. This was written for older version. Will update soon.

**Comment by Derancli** [comment]
That would be great. Thanks!

-- 
  Adam

**Comment by itsmepvr** [comment]
Updated for  <= v2.1.65.
