### ISSUE TITLE
anki problem

### ISSUE THREAD

**Issue by damooni** [itsmepvr/anki-find-and-replace-in-templates#4]
I change my anki with add-on find and replace and all of my card be destroyed i would be very appreciated if you can help me

I did this
find:(.*)
replace:"[sound:\1.mp3]"

and then all of my text card disappeared and i can not return to the first state
please help!!!!!!

**Comment by itsmepvr** [comment]
(.*) will actually replace all capture groups. I just like to know if this is intentional or what you are exactly trying to replace. And actually you can undo the find & replace by going to 'edit->undo find & replace'. This will undo all replaces.
