### ISSUE TITLE
Failing on start up on Apple Silicon Mac

### ISSUE THREAD

**Issue by ricodude** [itsmepvr/anki-find-and-replace-in-templates#7]
Using this install: anki-23.10.1-mac-apple-qt6.dmg. This is on an M3 MacBook Pro running 14.1.1. I get the below error message on start up:

<img width="612" alt="image" src="https://github.com/itsmepvr/anki-find-and-replace-in-templates/assets/19240432/2bef4c2e-649b-43b9-8348-d8272075cabc">

**Comment by itsmepvr** [comment]
Since I dont use mac I didnt tested in mac anytime. Might be the issue with Qt version I am using.  Need to update for latest release. Will do.

**Comment by nclvrps** [comment]
Probably @ricodude is getting this add-on from the Anki repository at [ankiweb.net/shared/info/992153575](https://ankiweb.net/shared/info/992153575) rather than here at Github. I think it still has the old version.

**Comment by itsmepvr** [comment]
I have updated Anki repo [ankiweb.net/shared/info/992153575](https://ankiweb.net/shared/info/992153575) with latest update

**Comment by ricodude** [comment]
Thx Venkata
